### ISSUE TITLE
which files are needed to run ?

### ISSUE THREAD

**Issue by tissatussa** [cristivlas/sturddle-chess-engine#3]
i managed to run `sturddle.py` in CuteChess, after i compiled the `.so` file .. i wonder which (py) files are needed to run, except those `.h` and `.cpp` etc. and folders, needed to compile. You kept all files mainly in root ..

**Comment by cristivlas** [comment]
Everything except .cpp, .h and .pyx files.

**Comment by tissatussa** [comment]
> Everything except .cpp, .h and .pyx files

i even deleted all folders, leaving only these root files (= bare minimum ?) :

```
__init__.py
book.bin
chess_engine.cpython-310-x86_64-linux-gnu.so
engine.py
nn-62ef826d1a6d.nnue
setup.py
sturddle.py    << start file
unit_test.py
worker.py
```

btw. i did not succeed building a one-file-binary, nor with setup.py nor with pyinstaller, i get errors ..

**Comment by cristivlas** [comment]
I have merged the dev branch into master, take a look at tools/build.py
